
version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://localhost:8080
    depends_on:
      - backend
    networks:
      - app-network

  # Placeholder for your backend service
  backend:
    image: your-backend-image:latest
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/flink-test-db
    depends_on:
      - mongo
    networks:
      - app-network
    # Uncomment when you have your backend ready
    # build:
    #   context: ./backend
    #   dockerfile: Dockerfile

  # MongoDB service
  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
